export const hightLawList = [
  // 'Báo cáo',
  // 'Chỉ thị',
  // 'Công điện',
  // 'Công ước',
  'Hiến pháp',
  // 'Hiệp định',
  // 'Hướng dẫn',
  // 'Kế hoạch',
  'Luật',
  'Lệnh',
  'Nghị quyết',
  'Nghị định',
  // 'Nghị định thư',
  'Pháp lệnh',
  // 'Quy chế',
  // 'Quy định',
  'Quyết định',
  // 'Thoả thuận',
  // 'Thông báo',
  // 'Thông tri',
  'Thông tư',
  'Thông tư liên tịch',
  // 'Văn bản WTO',
  // 'Văn bản hợp nhất',
  // 'Văn bản khác',
  // 'WTO_Cam kết VN',
  // 'WTO_Văn bản',
  // 'Điều lệ',
  // 'Điều ước',
  // 'Điều ước quốc tế',
];

export const skipLawDepartmentWord = [
  'Tỉnh',
  'Huyện',
  'Thành phố',
  'Quận',
  'Phường',
  'Xã',
];
