version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanghcmut/tnvl-backend-app
    image: kanghcmut/lvtn-backend-app:latest
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096  # Increase the memory limit to 4GB
    deploy:
      resources:
        limits:
          memory: 4g  # Limit the container to 4GB of memory