services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - dev-be-node-module:/workspace/node_modules
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo
    restart: always
    volumes:
      - law-dev-data:/data/db
volumes:
  law-dev-data:
  dev-be-node-module:
