FROM node:21-alpine

# Install git and bash for rum cmd in actions
RUN apk add --no-cache \
    git \
    bash

# Dev Environment:
    # Alpine linux distro: ✅
    # Node: ✅ (v.21)
    # Git: ✅
    # Bash: ✅